import crypto from 'node:crypto'
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import type { TerminalStatus } from '@tasktty/shared'
import type { CommandRunner } from './command.js'
import { runChecked } from './command.js'
import type { WorktreeSetupTask } from './setup.js'

export const generateTmuxSocketName = (): string =>
  `tasktty-wt-${crypto.randomBytes(8).toString('hex')}`
export const generateTmuxSessionName = (): string =>
  `tasktty-term-${crypto.randomBytes(8).toString('hex')}`

export interface LaunchSpec {
  argv: string[]
  cwd: string
  env: Record<string, string>
  setupTasks?: WorktreeSetupTask[]
  setupError?: string
}

export interface TmuxSessionState {
  status: TerminalStatus
  exitCode: number | null
}

export interface TmuxTerminalSession {
  id: string
  worktreeId: string
  name: string
  sessionName: string
  argv: string[]
  status: Exclude<TerminalStatus, 'missing'>
  exitCode: number | null
  createdAt: string
  updatedAt: string
}

export interface TmuxTerminalMetadata {
  terminalId: string
  worktreeId: string
  name: string
  argv: string[]
  createdAt: string
  updatedAt: string
}

const encodeMetadata = (value: unknown): string =>
  Buffer.from(JSON.stringify(value), 'utf8').toString('base64url')

function decodeMetadata(value: string): unknown {
  if (!value) {
    return undefined
  }

  return JSON.parse(Buffer.from(value, 'base64url').toString('utf8'))
}

export const TMUX_SCROLL_EXIT_SEQUENCE = '\u001b[9000~'
const TMUX_SCROLL_EXIT_KEY = TMUX_SCROLL_EXIT_SEQUENCE.replace(
  '\u001b',
  '\\033'
)

const TMUX_CONFIG = `# Generated by TaskTTY. This does not read or modify ~/.tmux.conf.
set -g status off
set -g default-terminal "tmux-256color"
set -s terminal-features[999] "xterm-256color:hyperlinks"
set -g extended-keys on
if-shell -F '#{>=:#{version},3.5}' 'set-option -s extended-keys-format csi-u'
set -g history-limit 50000
set -g remain-on-exit on
set -g exit-empty off
set -g focus-events on
set -g monitor-bell on
set -g bell-action any
set -g visual-bell off
set -g mouse on
set -g window-size latest
set -g destroy-unattached off
set -g mode-style "fg=default,bg=default"
set -s user-keys[0] "${TMUX_SCROLL_EXIT_KEY}"
bind-key -T root User0 select-pane -t .
bind-key -T copy-mode User0 send-keys -X cancel
bind-key -T copy-mode-vi User0 send-keys -X cancel
bind-key -T root WheelUpPane if-shell -F '#{||:#{alternate_on},#{pane_in_mode},#{mouse_any_flag}}' { send-keys -M } { copy-mode -He }
`

export class TmuxAdapter {
  readonly configPath: string
  readonly specsDir: string
  private readonly launcherPath: string

  constructor(
    private readonly runner: CommandRunner,
    private readonly runtimeDir: string,
    private readonly executable = 'tmux',
    launcherPath = fileURLToPath(new URL('./launcher.js', import.meta.url))
  ) {
    this.configPath = path.join(runtimeDir, 'tmux.conf')
    this.specsDir = path.join(runtimeDir, 'launch-specs')
    this.launcherPath = launcherPath
  }

  async initialize(): Promise<void> {
    await fs.mkdir(this.specsDir, { recursive: true, mode: 0o700 })
    await fs.writeFile(this.configPath, TMUX_CONFIG, { mode: 0o600 })
  }

  private base(socketName: string): string[] {
    return ['-L', socketName, '-f', this.configPath]
  }

  private environment(): NodeJS.ProcessEnv {
    const env = { ...process.env }
    delete env.TMUX
    delete env.TMUX_PANE
    return env
  }

  async createSession(input: {
    socketName: string
    sessionName: string
    terminalId: string
    worktreeId: string
    name: string
    createdAt: string
    cwd: string
    argv: string[]
    env: Record<string, string>
    setupTasks?: WorktreeSetupTask[]
    setupError?: string
  }): Promise<void> {
    await this.initialize()
    const specPath = path.join(this.specsDir, `${input.terminalId}.json`)
    const spec: LaunchSpec = {
      argv: [...input.argv],
      cwd: input.cwd,
      env: { ...input.env },
      ...(input.setupTasks?.length
        ? {
            setupTasks: input.setupTasks.map((task) => ({
              ...task,
              argv: [...task.argv],
              env: { ...task.env }
            }))
          }
        : {}),
      ...(input.setupError ? { setupError: input.setupError } : {})
    }
    await fs.writeFile(specPath, JSON.stringify(spec), { mode: 0o600 })
    let created = false
    try {
      await runChecked(this.runner, {
        executable: this.executable,
        args: [
          ...this.base(input.socketName),
          'new-session',
          '-d',
          '-s',
          input.sessionName,
          '-c',
          input.cwd,
          '--',
          process.execPath,
          this.launcherPath,
          specPath
        ],
        env: this.environment(),
        timeoutMs: 30_000
      })
      created = true
      await this.configureServer(input.socketName)
      await this.setTerminalMetadata(input.socketName, input.sessionName, {
        terminalId: input.terminalId,
        worktreeId: input.worktreeId,
        name: input.name,
        argv: input.argv,
        createdAt: input.createdAt,
        updatedAt: input.createdAt
      })
    } catch (error) {
      if (created) {
        await this.killSession(
          input.socketName,
          input.sessionName,
          input.terminalId
        ).catch(() => undefined)
      } else {
        await fs.unlink(specPath).catch(() => undefined)
      }

      throw error
    }
  }

  async configureServer(socketName: string): Promise<void> {
    await runChecked(this.runner, {
      executable: this.executable,
      args: [...this.base(socketName), 'source-file', this.configPath],
      env: this.environment(),
      timeoutMs: 10_000
    })
  }

  async setTerminalMetadata(
    socketName: string,
    sessionName: string,
    metadata: TmuxTerminalMetadata,
    onlyIfUnset = false
  ): Promise<void> {
    const values = [
      ['@tasktty-name', encodeMetadata(metadata.name)],
      ['@tasktty-argv', encodeMetadata(metadata.argv)],
      ['@tasktty-created-at', encodeMetadata(metadata.createdAt)],
      ['@tasktty-updated-at', encodeMetadata(metadata.updatedAt)],
      ['@tasktty-worktree-id', metadata.worktreeId],
      ['@tasktty-terminal-id', metadata.terminalId]
    ] as const
    for (const [key, value] of values) {
      const request = {
        executable: this.executable,
        args: [
          ...this.base(socketName),
          'set-option',
          ...(onlyIfUnset ? ['-o'] : []),
          '-t',
          sessionName,
          key,
          value
        ],
        env: this.environment(),
        timeoutMs: 10_000
      }
      if (!onlyIfUnset) {
        await runChecked(this.runner, request)
        continue
      }

      const result = await this.runner.run(request)
      if (result.exitCode !== 0 && !/already set/i.test(result.stderr)) {
        throw new Error(result.stderr.trim() || `Failed to set ${key}`)
      }
    }
  }

  async renameTerminal(
    socketName: string,
    sessionName: string,
    name: string,
    updatedAt: string
  ): Promise<void> {
    for (const [key, value] of [
      ['@tasktty-updated-at', encodeMetadata(updatedAt)],
      ['@tasktty-name', encodeMetadata(name)]
    ] as const) {
      await runChecked(this.runner, {
        executable: this.executable,
        args: [
          ...this.base(socketName),
          'set-option',
          '-t',
          sessionName,
          key,
          value
        ],
        env: this.environment(),
        timeoutMs: 10_000
      })
    }
  }

  async listSessions(socketName: string): Promise<TmuxTerminalSession[]> {
    const result = await this.runner.run({
      executable: this.executable,
      args: [
        ...this.base(socketName),
        'list-panes',
        '-a',
        '-F',
        '#{session_name}\t#{@tasktty-terminal-id}\t#{@tasktty-worktree-id}\t#{@tasktty-name}\t#{@tasktty-argv}\t#{@tasktty-created-at}\t#{@tasktty-updated-at}\t#{session_created}\t#{pane_dead}\t#{pane_dead_status}'
      ],
      env: this.environment(),
      timeoutMs: 10_000
    })
    if (result.exitCode !== 0) {
      if (
        /no server running|no sessions|failed to connect|error connecting to/i.test(
          result.stderr
        )
      ) {
        return []
      }

      throw new Error(
        result.stderr.trim() || 'Failed to list terminal sessions'
      )
    }

    const sessions = new Map<string, TmuxTerminalSession>()
    for (const line of result.stdout.split('\n')) {
      if (!line) {
        continue
      }

      const [
        sessionName,
        terminalId,
        worktreeId,
        encodedName,
        encodedArgv,
        encodedCreatedAt,
        encodedUpdatedAt,
        sessionCreated,
        paneDead,
        paneDeadStatus
      ] = line.split('\t')
      if (
        !sessionName ||
        !terminalId ||
        !worktreeId ||
        sessions.has(sessionName)
      ) {
        continue
      }

      try {
        const name = decodeMetadata(encodedName ?? '')
        const argv = decodeMetadata(encodedArgv ?? '')
        const createdAt = decodeMetadata(encodedCreatedAt ?? '')
        const updatedAt = decodeMetadata(encodedUpdatedAt ?? '')
        if (
          (name !== undefined && typeof name !== 'string') ||
          (argv !== undefined &&
            (!Array.isArray(argv) ||
              !argv.every((value) => typeof value === 'string'))) ||
          (createdAt !== undefined && typeof createdAt !== 'string') ||
          (updatedAt !== undefined && typeof updatedAt !== 'string')
        ) {
          continue
        }

        const fallbackCreatedAt =
          typeof createdAt === 'string'
            ? createdAt
            : new Date(Number(sessionCreated) * 1_000).toISOString()
        const dead = paneDead === '1'
        const exitCode =
          dead && paneDeadStatus ? Number.parseInt(paneDeadStatus, 10) : null
        sessions.set(sessionName, {
          id: terminalId,
          worktreeId,
          name: name ?? sessionName,
          sessionName,
          argv: argv ?? [],
          status: dead ? 'exited' : 'running',
          exitCode: Number.isNaN(exitCode) ? null : exitCode,
          createdAt: createdAt ?? fallbackCreatedAt,
          updatedAt: updatedAt ?? createdAt ?? fallbackCreatedAt
        })
      } catch {
        continue
      }
    }

    return [...sessions.values()]
  }

  async sessionState(
    socketName: string,
    sessionName: string
  ): Promise<TmuxSessionState> {
    const result = await this.runner.run({
      executable: this.executable,
      args: [
        ...this.base(socketName),
        'list-panes',
        '-t',
        sessionName,
        '-F',
        '#{pane_dead}\t#{pane_dead_status}'
      ],
      env: this.environment(),
      timeoutMs: 10_000
    })
    if (result.exitCode !== 0) {
      return { status: 'missing', exitCode: null }
    }

    const [dead, status] = result.stdout.trim().split('\t')
    if (dead === '1') {
      return {
        status: 'exited',
        exitCode: status ? Number.parseInt(status, 10) : null
      }
    }

    return { status: 'running', exitCode: null }
  }

  async sessionSize(
    socketName: string,
    sessionName: string
  ): Promise<{ cols: number; rows: number } | null> {
    const result = await this.runner.run({
      executable: this.executable,
      args: [
        ...this.base(socketName),
        'display-message',
        '-p',
        '-t',
        sessionName,
        '#{window_width}\t#{window_height}'
      ],
      env: this.environment(),
      timeoutMs: 10_000
    })
    if (result.exitCode !== 0) {
      return null
    }

    const [cols, rows] = result.stdout.trim().split('\t').map(Number)
    return cols && rows ? { cols, rows } : null
  }

  async sessionTitle(
    socketName: string,
    sessionName: string
  ): Promise<string | null> {
    const result = await this.runner.run({
      executable: this.executable,
      args: [
        ...this.base(socketName),
        'display-message',
        '-p',
        '-t',
        sessionName,
        '#{pane_title}'
      ],
      env: this.environment(),
      timeoutMs: 10_000
    })
    if (result.exitCode !== 0) {
      return null
    }

    return result.stdout.trim() || null
  }

  attachArgs(socketName: string, sessionName: string): string[] {
    return [...this.base(socketName), 'attach-session', '-t', sessionName]
  }

  async killSession(
    socketName: string,
    sessionName: string,
    terminalId?: string
  ): Promise<void> {
    const result = await this.runner.run({
      executable: this.executable,
      args: [...this.base(socketName), 'kill-session', '-t', sessionName],
      env: this.environment(),
      timeoutMs: 15_000
    })
    if (
      result.exitCode !== 0 &&
      !/no server running|can't find session|no sessions/i.test(result.stderr)
    ) {
      throw new Error(result.stderr.trim() || 'Failed to kill terminal session')
    }

    if (terminalId) {
      await fs
        .unlink(path.join(this.specsDir, `${terminalId}.json`))
        .catch(() => undefined)
    }

    const list = await this.runner.run({
      executable: this.executable,
      args: [...this.base(socketName), 'list-sessions'],
      env: this.environment(),
      timeoutMs: 10_000
    })
    if (list.exitCode !== 0 || !list.stdout.trim()) {
      await this.killServer(socketName)
    }
  }

  async killServer(socketName: string): Promise<void> {
    const terminalIds = (await this.listSessions(socketName)).map(
      (terminal) => terminal.id
    )
    const result = await this.runner.run({
      executable: this.executable,
      args: [...this.base(socketName), 'kill-server'],
      env: this.environment(),
      timeoutMs: 15_000
    })
    if (
      result.exitCode !== 0 &&
      !/no server running|no sessions/i.test(result.stderr)
    ) {
      throw new Error(
        result.stderr.trim() || 'Failed to kill worktree tmux server'
      )
    }

    await Promise.all(
      terminalIds.map((terminalId) =>
        fs
          .unlink(path.join(this.specsDir, `${terminalId}.json`))
          .catch(() => undefined)
      )
    )
  }
}
