import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { TerminalStatus } from "@tasktty/shared";
import type { CommandRunner } from "./command.js";
import { runChecked } from "./command.js";
import type { WorktreeSetupTask } from "./setup.js";

export const generateTmuxSocketName = (): string =>
  `tasktty-wt-${crypto.randomBytes(8).toString("hex")}`;
export const generateTmuxSessionName = (): string =>
  `tasktty-term-${crypto.randomBytes(8).toString("hex")}`;

export interface LaunchSpec {
  argv: string[];
  cwd: string;
  env: Record<string, string>;
  setupTasks?: WorktreeSetupTask[];
  setupError?: string;
}

export interface TmuxSessionState {
  status: TerminalStatus;
  exitCode: number | null;
}

export const TMUX_SCROLL_EXIT_SEQUENCE = "\u001b[9000~";
const TMUX_SCROLL_EXIT_KEY = TMUX_SCROLL_EXIT_SEQUENCE.replace("\u001b", "\\033");

const TMUX_CONFIG = `# Generated by TaskTTY. This does not read or modify ~/.tmux.conf.
set -g status off
set -g default-terminal "tmux-256color"
set -s terminal-features[999] "xterm-256color:hyperlinks"
set -g extended-keys on
if-shell -F '#{>=:#{version},3.5}' 'set-option -s extended-keys-format csi-u'
set -g history-limit 50000
set -g remain-on-exit on
set -g exit-empty off
set -g focus-events on
set -g monitor-bell on
set -g bell-action any
set -g visual-bell off
set -g mouse on
set -g window-size latest
set -g destroy-unattached off
set -g mode-style "fg=default,bg=default"
set -s user-keys[0] "${TMUX_SCROLL_EXIT_KEY}"
bind-key -T root User0 select-pane -t .
bind-key -T copy-mode User0 send-keys -X cancel
bind-key -T copy-mode-vi User0 send-keys -X cancel
bind-key -T root WheelUpPane if-shell -F '#{||:#{alternate_on},#{pane_in_mode},#{mouse_any_flag}}' { send-keys -M } { copy-mode -He }
`;

export class TmuxAdapter {
  readonly configPath: string;
  readonly specsDir: string;
  private readonly launcherPath: string;

  constructor(
    private readonly runner: CommandRunner,
    private readonly runtimeDir: string,
    private readonly executable = "tmux",
    launcherPath = fileURLToPath(new URL("./launcher.js", import.meta.url)),
  ) {
    this.configPath = path.join(runtimeDir, "tmux.conf");
    this.specsDir = path.join(runtimeDir, "launch-specs");
    this.launcherPath = launcherPath;
  }

  async initialize(): Promise<void> {
    await fs.mkdir(this.specsDir, { recursive: true, mode: 0o700 });
    await fs.writeFile(this.configPath, TMUX_CONFIG, { mode: 0o600 });
  }

  private base(socketName: string): string[] {
    return ["-L", socketName, "-f", this.configPath];
  }

  private environment(): NodeJS.ProcessEnv {
    const env = { ...process.env };
    delete env.TMUX;
    delete env.TMUX_PANE;
    return env;
  }

  async createSession(input: {
    socketName: string;
    sessionName: string;
    terminalId: string;
    worktreeId: string;
    cwd: string;
    argv: string[];
    env: Record<string, string>;
    setupTasks?: WorktreeSetupTask[];
    setupError?: string;
  }): Promise<void> {
    await this.initialize();
    const specPath = path.join(this.specsDir, `${input.terminalId}.json`);
    const spec: LaunchSpec = {
      argv: [...input.argv],
      cwd: input.cwd,
      env: { ...input.env },
      ...(input.setupTasks?.length
        ? {
            setupTasks: input.setupTasks.map((task) => ({
              ...task,
              argv: [...task.argv],
              env: { ...task.env },
            })),
          }
        : {}),
      ...(input.setupError ? { setupError: input.setupError } : {}),
    };
    await fs.writeFile(specPath, JSON.stringify(spec), { mode: 0o600 });
    let created = false;
    try {
      await runChecked(this.runner, {
        executable: this.executable,
        args: [
          ...this.base(input.socketName),
          "new-session",
          "-d",
          "-s",
          input.sessionName,
          "-c",
          input.cwd,
          "--",
          process.execPath,
          this.launcherPath,
          specPath,
        ],
        env: this.environment(),
        timeoutMs: 30_000,
      });
      created = true;
      await this.configureServer(input.socketName);
      await Promise.all([
        this.setMetadata(
          input.socketName,
          input.sessionName,
          "@tasktty-terminal-id",
          input.terminalId,
        ),
        this.setMetadata(
          input.socketName,
          input.sessionName,
          "@tasktty-worktree-id",
          input.worktreeId,
        ),
      ]);
    } catch (error) {
      if (created)
        await this.killSession(input.socketName, input.sessionName, input.terminalId).catch(
          () => undefined,
        );
      else await fs.unlink(specPath).catch(() => undefined);
      throw error;
    }
  }

  async configureServer(socketName: string): Promise<void> {
    await runChecked(this.runner, {
      executable: this.executable,
      args: [...this.base(socketName), "source-file", this.configPath],
      env: this.environment(),
      timeoutMs: 10_000,
    });
  }

  private async setMetadata(
    socketName: string,
    sessionName: string,
    key: string,
    value: string,
  ): Promise<void> {
    await runChecked(this.runner, {
      executable: this.executable,
      args: [...this.base(socketName), "set-option", "-t", sessionName, key, value],
      env: this.environment(),
      timeoutMs: 10_000,
    });
  }

  async sessionState(socketName: string, sessionName: string): Promise<TmuxSessionState> {
    const result = await this.runner.run({
      executable: this.executable,
      args: [
        ...this.base(socketName),
        "list-panes",
        "-t",
        sessionName,
        "-F",
        "#{pane_dead}\t#{pane_dead_status}",
      ],
      env: this.environment(),
      timeoutMs: 10_000,
    });
    if (result.exitCode !== 0) return { status: "missing", exitCode: null };
    const [dead, status] = result.stdout.trim().split("\t");
    if (dead === "1")
      return { status: "exited", exitCode: status ? Number.parseInt(status, 10) : null };
    return { status: "running", exitCode: null };
  }

  async sessionSize(
    socketName: string,
    sessionName: string,
  ): Promise<{ cols: number; rows: number } | null> {
    const result = await this.runner.run({
      executable: this.executable,
      args: [
        ...this.base(socketName),
        "display-message",
        "-p",
        "-t",
        sessionName,
        "#{window_width}\t#{window_height}",
      ],
      env: this.environment(),
      timeoutMs: 10_000,
    });
    if (result.exitCode !== 0) return null;
    const [cols, rows] = result.stdout.trim().split("\t").map(Number);
    return cols && rows ? { cols, rows } : null;
  }

  async sessionTitle(socketName: string, sessionName: string): Promise<string | null> {
    const result = await this.runner.run({
      executable: this.executable,
      args: [...this.base(socketName), "display-message", "-p", "-t", sessionName, "#{pane_title}"],
      env: this.environment(),
      timeoutMs: 10_000,
    });
    if (result.exitCode !== 0) return null;
    return result.stdout.trim() || null;
  }

  attachArgs(socketName: string, sessionName: string): string[] {
    return [...this.base(socketName), "attach-session", "-t", sessionName];
  }

  async killSession(socketName: string, sessionName: string, terminalId?: string): Promise<void> {
    const result = await this.runner.run({
      executable: this.executable,
      args: [...this.base(socketName), "kill-session", "-t", sessionName],
      env: this.environment(),
      timeoutMs: 15_000,
    });
    if (
      result.exitCode !== 0 &&
      !/no server running|can't find session|no sessions/i.test(result.stderr)
    ) {
      throw new Error(result.stderr.trim() || "Failed to kill terminal session");
    }
    if (terminalId)
      await fs.unlink(path.join(this.specsDir, `${terminalId}.json`)).catch(() => undefined);
    const list = await this.runner.run({
      executable: this.executable,
      args: [...this.base(socketName), "list-sessions"],
      env: this.environment(),
      timeoutMs: 10_000,
    });
    if (list.exitCode !== 0 || !list.stdout.trim()) await this.killServer(socketName);
  }

  async killServer(socketName: string): Promise<void> {
    const result = await this.runner.run({
      executable: this.executable,
      args: [...this.base(socketName), "kill-server"],
      env: this.environment(),
      timeoutMs: 15_000,
    });
    if (result.exitCode !== 0 && !/no server running|no sessions/i.test(result.stderr)) {
      throw new Error(result.stderr.trim() || "Failed to kill worktree tmux server");
    }
  }
}
