import crypto from 'node:crypto'
import fs from 'node:fs/promises'
import path from 'node:path'
import { z } from 'zod'
import {
  TERMINAL_SCROLL_EXIT_SEQUENCE,
  TERMINAL_SELECTION_CLEAR_SEQUENCE,
  TERMINAL_SELECTION_RESTORE_SEQUENCE,
  TERMINAL_SELECTION_START_SEQUENCE,
  TERMINAL_SELECTION_STOP_SEQUENCE,
  type TerminalSize,
  type TerminalStatus
} from '@treeport/shared'
import type { CommandRunner } from './command'
import { resolveExecutablePath, runChecked } from './command'
import { prepareShellIntegration } from './shell-integration'
import type { WorktreeSetupTask } from './setup'

export const generateTmuxSocketName = (): string =>
  `treeport-wt-${crypto.randomBytes(8).toString('hex')}`
export const generateTmuxSessionName = (): string =>
  `treeport-term-${crypto.randomBytes(8).toString('hex')}`

export interface LaunchSpec {
  argv: string[]
  initialTitle?: string | undefined
  fallbackArgv?: string[] | undefined
  cwd: string
  env: Record<string, string>
  shellIntegrationDir?: string | undefined
  tmuxExecutable?: string | undefined
  setupTasks?: WorktreeSetupTask[] | undefined
  setupError?: string | undefined
}

export interface TmuxSessionState {
  status: TerminalStatus
  exitCode: number | null
}

export interface TmuxSessionTitleState {
  paneTitle: string | null
  currentCommand: string | null
  commandLine?: string | null
  shellTitle?: string | null
  fallbackShell?: string | null
}

export interface TmuxTerminalSession {
  id: string
  worktreeId: string
  name: string
  sessionName: string
  argv: string[]
  shellCommand: string | null
  interactiveShell: boolean
  closeOnSuccess: boolean
  status: Exclude<TerminalStatus, 'missing'>
  exitCode: number | null
  createdAt: string
  updatedAt: string
}

export interface TmuxPaneProcess {
  pid: number
  terminalId: string
}

export interface TmuxTerminalMetadata {
  terminalId: string
  worktreeId: string
  name: string
  argv: string[]
  shellCommand: string | null
  interactiveShell: boolean
  closeOnSuccess: boolean
  createdAt: string
  updatedAt: string
}

interface DecodedTmuxMetadata {
  terminalId: string
  worktreeId: string
  name: string | undefined
  argv: string[] | undefined
  shellCommand: string | null | undefined
  createdAt: string | undefined
  updatedAt: string | undefined
}

type TmuxMetadataValue = string | readonly string[] | null

const encodeMetadata = (value: TmuxMetadataValue): string =>
  Buffer.from(JSON.stringify(value), 'utf8').toString('base64url')

function isAbsentTmuxServer(stderr: string): boolean {
  return (
    /no server running|no sessions|no current target/i.test(stderr) ||
    /(?:failed to connect|error connecting to).*(?:no such file or directory|connection refused)/i.test(
      stderr
    )
  )
}

function decodeMetadata<Output>(
  value: string,
  schema: z.ZodType<Output>
): Output | undefined {
  if (!value) {
    return undefined
  }

  return schema.parse(
    JSON.parse(Buffer.from(value, 'base64url').toString('utf8'))
  )
}

export const TMUX_SCROLL_EXIT_SEQUENCE = TERMINAL_SCROLL_EXIT_SEQUENCE
export const TMUX_SELECTION_CLEAR_SEQUENCE = TERMINAL_SELECTION_CLEAR_SEQUENCE
export const TMUX_SELECTION_RESTORE_SEQUENCE =
  TERMINAL_SELECTION_RESTORE_SEQUENCE
export const TMUX_SELECTION_START_SEQUENCE = TERMINAL_SELECTION_START_SEQUENCE
export const TMUX_SELECTION_STOP_SEQUENCE = TERMINAL_SELECTION_STOP_SEQUENCE
const TMUX_SCROLL_EXIT_KEY = TMUX_SCROLL_EXIT_SEQUENCE.replace(
  '\u001b',
  '\\033'
)
const TMUX_SELECTION_CLEAR_KEY = TMUX_SELECTION_CLEAR_SEQUENCE.replace(
  '\u001b',
  '\\033'
)
const TMUX_SELECTION_RESTORE_KEY = TMUX_SELECTION_RESTORE_SEQUENCE.replace(
  '\u001b',
  '\\033'
)
const TMUX_SELECTION_START_KEY = TMUX_SELECTION_START_SEQUENCE.replace(
  '\u001b',
  '\\033'
)
const TMUX_SELECTION_STOP_KEY = TMUX_SELECTION_STOP_SEQUENCE.replace(
  '\u001b',
  '\\033'
)
const TMUX_CONFIG = `# Generated by Treeport. This does not read or modify ~/.tmux.conf.
set -g status off
set -g default-terminal "tmux-256color"
set -s terminal-features[999] "xterm*:hyperlinks"
set -g extended-keys on
if-shell -F '#{>=:#{version},3.5}' 'set-option -s extended-keys-format csi-u'
set -g history-limit 50000
set -g remain-on-exit on
set -g exit-empty off
set -g focus-events on
set -g monitor-bell on
set -g bell-action any
set -g visual-bell off
set -g mouse on
set -g destroy-unattached off
set -g mode-style "fg=#09090b,bg=#f4f4f5"
set -s set-clipboard external
set -s user-keys[0] "${TMUX_SCROLL_EXIT_KEY}"
set -s user-keys[1] "${TMUX_SELECTION_START_KEY}"
set -s user-keys[2] "${TMUX_SELECTION_STOP_KEY}"
set -s user-keys[3] "${TMUX_SELECTION_CLEAR_KEY}"
set -s user-keys[4] "${TMUX_SELECTION_RESTORE_KEY}"
bind-key -T root User0 select-pane -t .
bind-key -T copy-mode User0 send-keys -X cancel
bind-key -T copy-mode-vi User0 send-keys -X cancel
bind-key -T root User1 copy-mode -H
bind-key -T copy-mode User1 send-keys -X clear-selection
bind-key -T copy-mode-vi User1 send-keys -X clear-selection
bind-key -T copy-mode User2 { send-keys -X copy-selection-no-clear ; send-keys -X stop-selection ; set-option -pF @treeport-selection-start-x '#{selection_start_x}' ; set-option -pF @treeport-selection-start-y '#{selection_start_y}' ; set-option -pF @treeport-selection-end-x '#{selection_end_x}' ; set-option -pF @treeport-selection-end-y '#{selection_end_y}' ; set-option -pF @treeport-selection-width '#{pane_width}' }
bind-key -T copy-mode-vi User2 { send-keys -X copy-selection-no-clear ; send-keys -X stop-selection ; set-option -pF @treeport-selection-start-x '#{selection_start_x}' ; set-option -pF @treeport-selection-start-y '#{selection_start_y}' ; set-option -pF @treeport-selection-end-x '#{selection_end_x}' ; set-option -pF @treeport-selection-end-y '#{selection_end_y}' ; set-option -pF @treeport-selection-width '#{pane_width}' }
bind-key -T root User3 { set-option -pu @treeport-selection-start-x ; set-option -pu @treeport-selection-start-y ; set-option -pu @treeport-selection-end-x ; set-option -pu @treeport-selection-end-y ; set-option -pu @treeport-selection-width }
bind-key -T copy-mode User3 { send-keys -X clear-selection ; set-option -pu @treeport-selection-start-x ; set-option -pu @treeport-selection-start-y ; set-option -pu @treeport-selection-end-x ; set-option -pu @treeport-selection-end-y ; set-option -pu @treeport-selection-width ; if-shell -F '#{==:#{scroll_position},0}' { send-keys -X cancel } }
bind-key -T copy-mode-vi User3 { send-keys -X clear-selection ; set-option -pu @treeport-selection-start-x ; set-option -pu @treeport-selection-start-y ; set-option -pu @treeport-selection-end-x ; set-option -pu @treeport-selection-end-y ; set-option -pu @treeport-selection-width ; if-shell -F '#{==:#{scroll_position},0}' { send-keys -X cancel } }
bind-key -T root User4 if-shell -F '#{||:#{alternate_on},#{mouse_any_flag}}' { select-pane -t . } { if-shell -F '#{==:#{@treeport-selection-width},#{pane_width}}' { copy-mode -H ; send-keys -X history-top ; if-shell -F '#{>:#{@treeport-selection-start-y},0}' { send-keys -X -N '#{@treeport-selection-start-y}' cursor-down } ; send-keys -X start-of-line ; if-shell -F '#{>:#{@treeport-selection-start-x},0}' { send-keys -X -N '#{@treeport-selection-start-x}' cursor-right } ; send-keys -X begin-selection ; send-keys -X history-top ; if-shell -F '#{>:#{@treeport-selection-end-y},0}' { send-keys -X -N '#{@treeport-selection-end-y}' cursor-down } ; send-keys -X start-of-line ; if-shell -F '#{>:#{@treeport-selection-end-x},0}' { send-keys -X -N '#{@treeport-selection-end-x}' cursor-right } ; send-keys -X stop-selection ; send-keys -X history-bottom } { copy-mode -H } }
bind-key -T copy-mode User4 select-pane -t .
bind-key -T copy-mode-vi User4 select-pane -t .
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X stop-selection
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X stop-selection
# Keep these explicit so source-file replaces stale bindings in existing servers.
bind-key -T copy-mode WheelUpPane { select-pane ; send-keys -X -N 1 scroll-up }
bind-key -T copy-mode-vi WheelUpPane { select-pane ; send-keys -X -N 1 scroll-up }
bind-key -T copy-mode WheelDownPane { select-pane ; send-keys -X -N 1 scroll-down ; if-shell -F '#{&&:#{==:#{scroll_position},0},#{==:#{selection_present},0}}' { send-keys -X cancel } }
bind-key -T copy-mode-vi WheelDownPane { select-pane ; send-keys -X -N 1 scroll-down ; if-shell -F '#{&&:#{==:#{scroll_position},0},#{==:#{selection_present},0}}' { send-keys -X cancel } }
bind-key -T root WheelUpPane if-shell -F '#{||:#{alternate_on},#{pane_in_mode},#{mouse_any_flag}}' { send-keys -M } { copy-mode -H }
`

export class TmuxAdapter {
  readonly configPath: string
  readonly specsDir: string
  readonly shellIntegrationDir: string
  private readonly launcherPath: string | undefined
  private readonly hostEnvironment: NodeJS.ProcessEnv
  private readonly platform: NodeJS.Platform
  private readonly uid: number | undefined
  private readonly creationTails = new Map<string, Promise<void>>()
  private readonly configuredSockets = new Set<string>()
  private readonly socketConfigurationPromises = new Map<
    string,
    Promise<void>
  >()
  private initializationPromise: Promise<boolean> | null = null
  private sshAuthSockPromise: Promise<string | undefined> | null = null

  constructor(
    private readonly runner: CommandRunner,
    private readonly runtimeDir: string,
    private readonly executable = 'tmux',
    launcherPath?: string,
    host: {
      environment?: NodeJS.ProcessEnv
      platform?: NodeJS.Platform
      uid?: number
    } = {}
  ) {
    this.configPath = path.join(runtimeDir, 'tmux.conf')
    this.specsDir = path.join(runtimeDir, 'launch-specs')
    this.shellIntegrationDir = path.join(runtimeDir, 'shell-integration')
    this.launcherPath = launcherPath
    this.hostEnvironment = host.environment ?? process.env
    this.platform = host.platform ?? process.platform
    this.uid = host.uid ?? process.getuid?.()
  }

  initialize(): Promise<boolean> {
    if (!this.initializationPromise) {
      this.initializationPromise = fs
        .mkdir(this.specsDir, { recursive: true, mode: 0o700 })
        .then(() =>
          Promise.all([
            fs.writeFile(this.configPath, TMUX_CONFIG, { mode: 0o600 }),
            prepareShellIntegration(this.shellIntegrationDir).then(
              () => true,
              () => false
            )
          ])
        )
        .then(([, shellIntegrationReady]) => shellIntegrationReady)
    }

    return this.initializationPromise
  }

  private base(socketName: string): string[] {
    return ['-L', socketName, '-f', this.configPath]
  }

  private environment(): NodeJS.ProcessEnv {
    const env = { ...this.hostEnvironment }
    delete env.TMUX
    delete env.TMUX_PANE
    return env
  }

  async createSession(input: {
    socketName: string
    sessionName: string
    terminalId: string
    worktreeId: string
    name: string
    createdAt: string
    cwd: string
    argv: string[]
    initialTitle?: string
    shellCommand: string | null
    interactiveShell: boolean
    fallbackArgv?: string[]
    closeOnSuccess?: boolean
    initialSize?: TerminalSize
    env: Record<string, string>
    setupTasks?: WorktreeSetupTask[]
    setupError?: string
  }): Promise<void> {
    if (!this.launcherPath) {
      throw new Error('A launcher path is required to create a tmux session')
    }

    const previousCreation =
      this.creationTails.get(input.socketName) ?? Promise.resolve()
    let releaseCreation!: () => void
    const creationGate = new Promise<void>((resolve) => {
      releaseCreation = resolve
    })
    const creationTail = previousCreation.then(() => creationGate)
    this.creationTails.set(input.socketName, creationTail)
    await previousCreation

    try {
      const shellIntegrationReady = await this.initialize()
      if (!this.sshAuthSockPromise) {
        const inherited = this.hostEnvironment.SSH_AUTH_SOCK?.trim()
        this.sshAuthSockPromise = inherited
          ? Promise.resolve(inherited)
          : this.platform === 'darwin' && this.uid !== undefined
            ? this.runner
                .run({
                  executable: '/bin/launchctl',
                  args: [
                    'asuser',
                    String(this.uid),
                    '/bin/launchctl',
                    'getenv',
                    'SSH_AUTH_SOCK'
                  ],
                  env: this.environment(),
                  timeoutMs: 10_000
                })
                .then((result) =>
                  result.exitCode === 0
                    ? result.stdout.trim() || undefined
                    : undefined
                )
                .catch(() => undefined)
            : Promise.resolve(undefined)
      }

      const sshAuthSock = await this.sshAuthSockPromise

      let startedServer = false
      const specPath = path.join(this.specsDir, `${input.terminalId}.json`)
      let created = false
      let wroteSpec = false
      try {
        if (!this.configuredSockets.has(input.socketName)) {
          const serverProbe = await this.runner.run({
            executable: this.executable,
            args: [
              ...this.base(input.socketName),
              'show-options',
              '-gv',
              'exit-empty'
            ],
            env: this.environment(),
            timeoutMs: 10_000
          })
          startedServer =
            serverProbe.exitCode !== 0 && isAbsentTmuxServer(serverProbe.stderr)
          await runChecked(this.runner, {
            executable: this.executable,
            args: [...this.base(input.socketName), 'start-server'],
            env: this.environment(),
            timeoutMs: 10_000
          })
          await this.configureServer(input.socketName)
        }

        const environment = { ...input.env }
        if (sshAuthSock) {
          environment.SSH_AUTH_SOCK = sshAuthSock
        }

        const spec: LaunchSpec = {
          argv: [...input.argv],
          cwd: input.cwd,
          env: environment
        }
        if (input.initialTitle) {
          spec.initialTitle = input.initialTitle
        }

        if (input.fallbackArgv) {
          spec.fallbackArgv = [...input.fallbackArgv]
        }

        spec.tmuxExecutable = resolveExecutablePath(
          this.executable,
          this.hostEnvironment
        )
        if (shellIntegrationReady) {
          spec.shellIntegrationDir = this.shellIntegrationDir
        }

        if (input.setupTasks?.length) {
          spec.setupTasks = input.setupTasks.map((task) => ({
            ...task,
            argv: [...task.argv],
            env: { ...task.env }
          }))
        }

        if (input.setupError) {
          spec.setupError = input.setupError
        }

        await fs.writeFile(specPath, JSON.stringify(spec), { mode: 0o600 })
        wroteSpec = true
        await runChecked(this.runner, {
          executable: this.executable,
          args: [
            ...this.base(input.socketName),
            'new-session',
            '-d',
            '-s',
            input.sessionName,
            ...(input.initialSize
              ? [
                  '-x',
                  String(input.initialSize.cols),
                  '-y',
                  String(input.initialSize.rows)
                ]
              : []),
            '-c',
            input.cwd,
            '--',
            process.execPath,
            this.launcherPath,
            specPath
          ],
          env: this.environment(),
          timeoutMs: 30_000
        })
        created = true
        await this.configureSession(input.socketName, input.sessionName, {
          terminalId: input.terminalId,
          worktreeId: input.worktreeId,
          name: input.name,
          argv: input.argv,
          shellCommand: input.shellCommand,
          interactiveShell: input.interactiveShell,
          closeOnSuccess: input.closeOnSuccess ?? false,
          createdAt: input.createdAt,
          updatedAt: input.createdAt
        })
      } catch (error) {
        if (created) {
          await this.killSession(
            input.socketName,
            input.sessionName,
            input.terminalId
          ).catch(() => undefined)
        } else if (wroteSpec) {
          await fs.unlink(specPath).catch(() => undefined)
        }

        if (!created && startedServer) {
          await this.runner.run({
            executable: this.executable,
            args: [
              ...this.base(input.socketName),
              'if-shell',
              '-F',
              '#{==:#{session_count},0}',
              'kill-server'
            ],
            env: this.environment(),
            timeoutMs: 10_000
          })
        }

        throw error
      }
    } finally {
      releaseCreation()
      if (this.creationTails.get(input.socketName) === creationTail) {
        this.creationTails.delete(input.socketName)
      }
    }
  }

  async configureServer(socketName: string): Promise<void> {
    if (this.configuredSockets.has(socketName)) {
      return
    }

    const existing = this.socketConfigurationPromises.get(socketName)
    if (existing) {
      return existing
    }

    const configuring = runChecked(this.runner, {
      executable: this.executable,
      args: [...this.base(socketName), 'source-file', this.configPath],
      env: this.environment(),
      timeoutMs: 10_000
    }).then(() => {
      this.configuredSockets.add(socketName)
    })
    this.socketConfigurationPromises.set(socketName, configuring)
    return configuring.finally(() => {
      if (this.socketConfigurationPromises.get(socketName) === configuring) {
        this.socketConfigurationPromises.delete(socketName)
      }
    })
  }

  private async configureSession(
    socketName: string,
    sessionName: string,
    metadata: TmuxTerminalMetadata
  ): Promise<void> {
    const values = [
      ['@treeport-name', encodeMetadata(metadata.name)],
      ['@treeport-argv', encodeMetadata(metadata.argv)],
      ['@treeport-shell-command', encodeMetadata(metadata.shellCommand)],
      ['@treeport-interactive-shell', metadata.interactiveShell ? '1' : '0'],
      ['@treeport-close-on-success', metadata.closeOnSuccess ? '1' : '0'],
      ['@treeport-created-at', encodeMetadata(metadata.createdAt)],
      ['@treeport-updated-at', encodeMetadata(metadata.updatedAt)],
      ['@treeport-worktree-id', metadata.worktreeId],
      ['@treeport-terminal-id', metadata.terminalId]
    ] as const
    await runChecked(this.runner, {
      executable: this.executable,
      args: [
        ...this.base(socketName),
        'set-option',
        '-w',
        '-t',
        sessionName,
        'window-size',
        'manual',
        ...values.flatMap(([key, value]) => [
          ';',
          'set-option',
          '-t',
          sessionName,
          key,
          value
        ])
      ],
      env: this.environment(),
      timeoutMs: 10_000
    })
  }

  async renameTerminal(
    socketName: string,
    sessionName: string,
    name: string,
    updatedAt: string
  ): Promise<void> {
    for (const [key, value] of [
      ['@treeport-updated-at', encodeMetadata(updatedAt)],
      ['@treeport-name', encodeMetadata(name)]
    ] as const) {
      await runChecked(this.runner, {
        executable: this.executable,
        args: [
          ...this.base(socketName),
          'set-option',
          '-t',
          sessionName,
          key,
          value
        ],
        env: this.environment(),
        timeoutMs: 10_000
      })
    }
  }

  async listSessions(socketName: string): Promise<TmuxTerminalSession[]> {
    const result = await this.runner.run({
      executable: this.executable,
      args: [
        ...this.base(socketName),
        'list-panes',
        '-a',
        '-F',
        '#{session_name}\t#{@treeport-terminal-id}\t#{@treeport-worktree-id}\t#{@treeport-name}\t#{@treeport-argv}\t#{@treeport-shell-command}\t#{@treeport-interactive-shell}\t#{@treeport-close-on-success}\t#{@treeport-created-at}\t#{@treeport-updated-at}\t#{session_created}\t#{pane_dead}\t#{pane_dead_status}'
      ],
      env: this.environment(),
      timeoutMs: 10_000
    })
    if (result.exitCode !== 0) {
      if (isAbsentTmuxServer(result.stderr)) {
        return []
      }

      throw new Error(
        result.stderr.trim() || 'Failed to list terminal sessions'
      )
    }

    const sessions = new Map<string, TmuxTerminalSession>()
    for (const line of result.stdout.split('\n')) {
      if (!line) {
        continue
      }

      const fields = line.split('\t')
      const [
        sessionName,
        terminalId,
        worktreeId,
        encodedName,
        encodedArgv,
        encodedShellCommand,
        encodedInteractiveShell,
        closeOnSuccess,
        encodedCreatedAt,
        encodedUpdatedAt,
        sessionCreated,
        paneDead,
        paneDeadStatus
      ] = fields
      if (
        !sessionName ||
        sessions.has(sessionName) ||
        !terminalId ||
        !worktreeId
      ) {
        continue
      }

      let metadata: DecodedTmuxMetadata
      try {
        metadata = {
          terminalId,
          worktreeId,
          name: decodeMetadata(encodedName ?? '', z.string()),
          argv: decodeMetadata(encodedArgv ?? '', z.array(z.string())),
          shellCommand: decodeMetadata(
            encodedShellCommand ?? '',
            z.string().nullable()
          ),
          createdAt: decodeMetadata(encodedCreatedAt ?? '', z.string()),
          updatedAt: decodeMetadata(encodedUpdatedAt ?? '', z.string())
        }
      } catch {
        continue
      }

      const interactiveShell =
        encodedInteractiveShell === '1'
          ? true
          : encodedInteractiveShell === '0'
            ? false
            : undefined
      if (
        metadata.shellCommand === undefined ||
        interactiveShell === undefined
      ) {
        continue
      }

      const fallbackCreatedAt =
        metadata.createdAt ??
        new Date(Number(sessionCreated) * 1_000).toISOString()
      const dead = paneDead === '1'
      const exitCode =
        dead && paneDeadStatus ? Number.parseInt(paneDeadStatus, 10) : null
      sessions.set(sessionName, {
        id: metadata.terminalId,
        worktreeId: metadata.worktreeId,
        name: metadata.name ?? sessionName,
        sessionName,
        argv: metadata.argv ?? [],
        shellCommand: metadata.shellCommand,
        interactiveShell,
        closeOnSuccess: closeOnSuccess === '1',
        status: dead ? 'exited' : 'running',
        exitCode: Number.isNaN(exitCode) ? null : exitCode,
        createdAt: fallbackCreatedAt,
        updatedAt: metadata.updatedAt ?? metadata.createdAt ?? fallbackCreatedAt
      })
    }

    return [...sessions.values()]
  }

  async listPaneProcesses(
    socketName: string,
    worktreeId: string
  ): Promise<TmuxPaneProcess[]> {
    const result = await this.runner.run({
      executable: this.executable,
      args: [
        ...this.base(socketName),
        'list-panes',
        '-a',
        '-F',
        '#{pane_pid}\t#{@treeport-terminal-id}\t#{@treeport-worktree-id}\t#{pane_dead}'
      ],
      env: this.environment(),
      timeoutMs: 10_000
    })
    if (result.exitCode !== 0) {
      if (isAbsentTmuxServer(result.stderr)) {
        return []
      }

      throw new Error(
        result.stderr.trim() || 'Failed to list terminal processes'
      )
    }

    const panes = new Map<number, TmuxPaneProcess>()
    for (const line of result.stdout.split('\n')) {
      const [pidText, terminalId, paneWorktreeId, dead] = line.split('\t')
      const pid = Number.parseInt(pidText ?? '', 10)
      if (
        !Number.isInteger(pid) ||
        pid <= 0 ||
        !terminalId ||
        paneWorktreeId !== worktreeId ||
        dead !== '0'
      ) {
        continue
      }

      panes.set(pid, { pid, terminalId })
    }
    return [...panes.values()].sort((left, right) => left.pid - right.pid)
  }

  async sessionState(
    socketName: string,
    sessionName: string
  ): Promise<TmuxSessionState> {
    const result = await this.runner.run({
      executable: this.executable,
      args: [
        ...this.base(socketName),
        'list-panes',
        '-t',
        sessionName,
        '-F',
        '#{pane_dead}\t#{pane_dead_status}'
      ],
      env: this.environment(),
      timeoutMs: 10_000
    })
    if (result.exitCode !== 0) {
      return { status: 'missing', exitCode: null }
    }

    const [dead, status] = result.stdout.trim().split('\t')
    if (dead === '1') {
      return {
        status: 'exited',
        exitCode: status ? Number.parseInt(status, 10) : null
      }
    }

    return { status: 'running', exitCode: null }
  }

  async capturePane(
    socketName: string,
    sessionName: string,
    lines: number
  ): Promise<string | null> {
    const result = await this.runner.run({
      executable: this.executable,
      args: [
        ...this.base(socketName),
        'capture-pane',
        '-p',
        '-S',
        `-${lines}`,
        '-t',
        sessionName
      ],
      env: this.environment(),
      timeoutMs: 10_000
    })
    if (result.exitCode !== 0) {
      if (
        isAbsentTmuxServer(result.stderr) ||
        /can't find (?:pane|session|window)/i.test(result.stderr)
      ) {
        return null
      }

      throw new Error(result.stderr.trim() || 'Failed to capture terminal pane')
    }

    const rows = result.stdout.split('\n')
    while (rows.length && /^[\t\r ]*$/.test(rows.at(-1)!)) {
      rows.pop()
    }

    return rows.slice(-lines).join('\n')
  }

  async useManualWindowSize(
    socketName: string,
    sessionName: string
  ): Promise<void> {
    await runChecked(this.runner, {
      executable: this.executable,
      args: [
        ...this.base(socketName),
        'set-option',
        '-w',
        '-t',
        sessionName,
        'window-size',
        'manual'
      ],
      env: this.environment(),
      timeoutMs: 10_000
    })
  }

  async resizeWindow(
    socketName: string,
    sessionName: string,
    cols: number,
    rows: number
  ): Promise<void> {
    await runChecked(this.runner, {
      executable: this.executable,
      args: [
        ...this.base(socketName),
        'resize-window',
        '-t',
        sessionName,
        '-x',
        String(cols),
        '-y',
        String(rows)
      ],
      env: this.environment(),
      timeoutMs: 10_000
    })
  }

  async sessionSize(
    socketName: string,
    sessionName: string
  ): Promise<{ cols: number; rows: number } | null> {
    const result = await this.runner.run({
      executable: this.executable,
      args: [
        ...this.base(socketName),
        'display-message',
        '-p',
        '-t',
        sessionName,
        '#{window_width}\t#{window_height}'
      ],
      env: this.environment(),
      timeoutMs: 10_000
    })
    if (result.exitCode !== 0) {
      return null
    }

    const [cols, rows] = result.stdout.trim().split('\t').map(Number)
    return cols && rows ? { cols, rows } : null
  }

  async sessionTitleState(
    socketName: string,
    sessionName: string
  ): Promise<TmuxSessionTitleState | null> {
    const result = await this.runner.run({
      executable: this.executable,
      args: [
        ...this.base(socketName),
        'display-message',
        '-p',
        '-t',
        sessionName,
        '#{@treeport-fallback-shell}\t#{@treeport-shell-title}\t#{pane_current_command}\t#{@treeport-command}\t#{pane_title}'
      ],
      env: this.environment(),
      timeoutMs: 10_000
    })
    if (result.exitCode !== 0) {
      return null
    }

    const firstSeparator = result.stdout.indexOf('\t')
    const secondSeparator = result.stdout.indexOf('\t', firstSeparator + 1)
    const thirdSeparator = result.stdout.indexOf('\t', secondSeparator + 1)
    const fourthSeparator = result.stdout.indexOf('\t', thirdSeparator + 1)
    if (
      firstSeparator === -1 ||
      secondSeparator === -1 ||
      thirdSeparator === -1 ||
      fourthSeparator === -1
    ) {
      return null
    }

    let fallbackShell: string | null = null
    let shellTitle: string | null = null
    try {
      fallbackShell =
        decodeMetadata(
          result.stdout.slice(0, firstSeparator).trim(),
          z.string()
        ) ?? null
      shellTitle =
        decodeMetadata(
          result.stdout.slice(firstSeparator + 1, secondSeparator).trim(),
          z.string()
        ) ?? null
    } catch {
      // Ignore malformed optional metadata from an external session.
    }

    const currentCommand =
      result.stdout.slice(secondSeparator + 1, thirdSeparator).trim() || null
    const commandLine =
      result.stdout.slice(thirdSeparator + 1, fourthSeparator).trim() || null
    const paneTitle = result.stdout.slice(fourthSeparator + 1).trim() || null
    return {
      paneTitle,
      currentCommand,
      commandLine,
      shellTitle,
      fallbackShell
    }
  }

  async setSessionShellTitle(
    socketName: string,
    sessionName: string,
    title: string | null
  ): Promise<void> {
    await runChecked(this.runner, {
      executable: this.executable,
      args: [
        ...this.base(socketName),
        'set-option',
        '-t',
        sessionName,
        '@treeport-shell-title',
        encodeMetadata(title)
      ],
      env: this.environment(),
      timeoutMs: 10_000
    })
  }

  async sessionTitle(
    socketName: string,
    sessionName: string
  ): Promise<string | null> {
    return (
      (await this.sessionTitleState(socketName, sessionName))?.paneTitle ?? null
    )
  }

  attachArgs(socketName: string, sessionName: string): string[] {
    return [...this.base(socketName), 'attach-session', '-t', sessionName]
  }

  async killSession(
    socketName: string,
    sessionName: string,
    terminalId?: string,
    options: { preserveServer?: boolean } = {}
  ): Promise<void> {
    const result = await this.runner.run({
      executable: this.executable,
      args: [...this.base(socketName), 'kill-session', '-t', sessionName],
      env: this.environment(),
      timeoutMs: 15_000
    })
    if (
      result.exitCode !== 0 &&
      !/no server running|can't find session|no sessions/i.test(result.stderr)
    ) {
      throw new Error(result.stderr.trim() || 'Failed to kill terminal session')
    }

    if (terminalId) {
      await fs
        .unlink(path.join(this.specsDir, `${terminalId}.json`))
        .catch(() => undefined)
    }

    if (!options.preserveServer) {
      const list = await this.runner.run({
        executable: this.executable,
        args: [...this.base(socketName), 'list-sessions'],
        env: this.environment(),
        timeoutMs: 10_000
      })
      if (list.exitCode !== 0 || !list.stdout.trim()) {
        await this.killServer(socketName)
      }
    }
  }

  async killServer(socketName: string): Promise<string[]> {
    const terminalIds = (await this.listSessions(socketName)).map(
      (terminal) => terminal.id
    )
    const result = await this.runner.run({
      executable: this.executable,
      args: [...this.base(socketName), 'kill-server'],
      env: this.environment(),
      timeoutMs: 15_000
    })
    if (result.exitCode !== 0 && !isAbsentTmuxServer(result.stderr)) {
      throw new Error(result.stderr.trim() || 'Failed to kill tree tmux server')
    }

    await Promise.all(
      terminalIds.map((terminalId) =>
        fs
          .unlink(path.join(this.specsDir, `${terminalId}.json`))
          .catch(() => undefined)
      )
    )
    this.configuredSockets.delete(socketName)
    return terminalIds
  }
}

export type TerminalSessionBackend = Pick<
  TmuxAdapter,
  | 'initialize'
  | 'configureServer'
  | 'createSession'
  | 'renameTerminal'
  | 'listSessions'
  | 'listPaneProcesses'
  | 'sessionState'
  | 'capturePane'
  | 'killSession'
  | 'killServer'
>
